### ISSUE TITLE
Upgrading to your forked version

### ISSUE THREAD

**Issue by ChrisLanks** [nefty1029/openwrt-optimized-archer-c7-v2#1]
Hey Nefty.
First off, awesome job for maintaining this stuff. I really appreciate it as does the community. I am noob when it comes to installing firmware on routers and I really do not want to brick my router here. I am trying to learn more.  My question is, how do i update from shunjou  version to yours?
Based on what I am seeing, you have the sha/tag in the build script. Do i log into my router, cd /tmp, git clone this repo, and run your build script? Then run the upgrade.bin it produces? Or do you apply the .patch files a different way? Any help would be appreciated. I know people are busy, so I understand.  If you can help, thanks again.

Chris

**Comment by nefty1029** [comment]
Sorry for the late reply. When upgrading from shunjou, I Just flash the sysupgrade.bin in LUCI. 
The instructions in the readme are those who are still using ar71xx system. 
Since you are using shunjou 's build, I would assume that your system has been migrated to the ath79., per his instructions.
Though to be safe, just make a backup of your settings, flash your system without keeping settings, then restore your settings through LUCI, since there have been many changes since shunjou  build.
If you are still unsure, just follow the migration process to ath79 in the readme.

**Comment by nefty1029** [comment]
Regarding the build script, you may want to ask vurrut for that, since he was the one who originally made it. The only changes that I have made is regarding the Openwrt version. 
You do not need to run the build script to upgrade your router, just download the latest files from my release page.

**Comment by ChrisLanks** [comment]
Hey nefty1029,
All good. You replied quickly! So I have shunjou's version installed and I have upgraded to ath29. I know you can do it in LUCI, but I just ssh'ed in and ran the instructions. It worked great.  I figured you would also need to run the sysupgrade.bin via ssh/LUCI. What I was missing is that the binary is in your release page -_-. I completely forgot to check that as I was used to other repos, which just checked in the binary to the code. 
Thanks for the update and feedback. Also thank you again for supplying this. Keep up the good work!
